"""Generate review markdown from a ReviewResult.

Lives in core/ so it can be used by both the agent layer (for memory
persistence) and the CLI layer (for artifact saving) without circular
imports.
"""

from __future__ import annotations

from datetime import datetime

from deep_hook_review.core.models import Issue, ReviewResult


def generate_review_markdown(result: ReviewResult) -> str:
    """Build a complete markdown document from a ``ReviewResult``."""
    lines = [
        "# Code Review",
        "",
        f"*Generated by Deek Hook - Review on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
    ]

    lines.append("## TL;DR\n")
    for b in result.tldr:
        lines.append(f"- {b}")
    lines.append("")

    if result.context:
        lines += ["## Context\n", result.context, ""]

    if result.walkthrough:
        lines += ["## Walkthrough\n", "| File | Change |", "|------|--------|"]
        for w in result.walkthrough:
            lines.append(f"| `{w.file}` | {w.change} |")
        lines.append("")

    lines.append("## Issues\n")
    _md_issues(lines, "Critical", result.critical)
    _md_issues(lines, "Warnings", result.warnings)
    _md_issues(lines, "Suggestions", result.suggestions)

    if result.flow:
        lines += ["## Flow\n", result.flow, ""]

    lines.append("## Checklist\n")
    actionable = result.critical + result.warnings
    if actionable:
        for i in result.critical:
            lines.append(f"- [ ] Fix: `{i.location}` — {i.message}")
        for i in result.warnings:
            lines.append(f"- [ ] Consider: `{i.location}` — {i.message}")
    else:
        lines.append("- [x] No critical issues")
    lines.append("")

    return "\n".join(lines)


def _md_issues(lines: list[str], heading: str, issues: list[Issue]) -> None:
    lines.append(f"### {heading}\n")
    if issues:
        for i in issues:
            lines.append(f"- `{i.location}` — {i.message}")
    else:
        lines.append("None")
    lines.append("")


def format_previous_review(result: ReviewResult) -> str:
    """Format a ReviewResult as a concise summary for use as previous_review (memory).

    Use this when passing the last review back into run_review(..., previous_review=...)
    so the model can check if those issues were addressed.
    """
    if not result.issues:
        return ""
    lines: list[str] = []
    for i in result.issues:
        lines.append(f"- `{i.location}` [{i.severity.value}] {i.message}")
    return "\n".join(lines)
